import 'package:flutter/material.dart';
import 'package:fridge_pantry_dj/screens/08_magic_recommendations_screen.dart';
import 'package:fridge_pantry_dj/screens/09_nutripal_screen.dart';
import 'package:fridge_pantry_dj/screens/10_shop_around_screen.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by flutterfire

// These import your custom screens
import 'screens/01_welcome_screen.dart';
import 'screens/02_login_screen.dart';
import 'screens/03_register_screen.dart';
import 'screens/04_main_menu_screen.dart';
import 'screens/05_settings_screen.dart';
import 'screens/06_add_ingredients_screen.dart';
import 'screens/07_recipe_mixer_screen.dart';
import 'screens/07.1_recipe_viewer_screen.dart';
import 'screens/07.2_saved_recipe_screen.dart';

import 'package:flutter_dotenv/flutter_dotenv.dart';

// where  app starts running
Future<void> main() async {
  await dotenv.load(fileName: "secrets.env");
  //Initialize flutter and Initialize Firebase
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  // runApp() tells Flutter to launch  app, starting with MyApp
  runApp(const MyApp());
}

// main widget for  whole application
class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This method builds the main structure
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Fridge & Pantry',

      // The overall color theme of  app
      theme: ThemeData(primarySwatch: Colors.teal),

      // first screen users will see when the app opens
      home: const WelcomeScreen(),

      // named routes for navigation
      routes: {
        // navigate to '/login' ,show the LoginScreen
        '/login': (_) => const LoginScreen(),
        // navigate to '/register', show the RegisterScreen
        '/register': (_) => const RegisterScreen(),
        '/main-menu': (_) => const MainMenuScreen(),
        //navigates to SettingsScreen()
        '/settings': (_) => const SettingsScreen(),
        '/add-ingredients': (_) => const AddIngredientsScreen(),
        '/recipe-mixer': (_) => const RecipeMixerScreen(),
        '/recipe-viewer': (_) => const RecipeViewerScreen(),
        '/recipe-saved': (_) => const SavedRecipesScreen(),

        '/nutripal': (_) => const NutripalScreen(),
        '/shop-around': (_) => const ShopAroundScreen(),
        '/magic-recommendations': (_) => const MagicRecommendationsScreen(),
      },
    );
  }
}
